<font size="6">Data Engineering Project — Retail Store Part 1 — Web Scraping</font>

In [1]:
from bs4 import BeautifulSoup
import pandas as pd
import requests

In [2]:
class scrape():
    def scrape_html(self,base_url, page):
        
        
        self.base_url = base_url
        self.page = page
        
        
        url = base_url + '?pg=' + str(page)
        r = requests.get(url)
        soup = BeautifulSoup(r.content, 'html')

        return soup
    
    def get_contents(self,soup):
        self.soup=soup
        
       
        products_content=soup.find_all('div',class_='product-card__content')
        return products_content
    
    def get_price_info(self,soup):
        self.soup=soup
        
       
        products_info=soup.find_all('div',class_='product-card__data')
        return products_info
        
        
        
    def get_names(self,content):
        self.content=content
        
        products_names=[]
        for product in content:
            name=product.find('p' , class_='product-card__name')
            products_names.append(name.get_text())
            
            
        return products_names    
    
    def get_percent(self,products_content):
        self.products_content=products_content
        
        
        list_percent=[]
        
        for product in products_content:
             meta=product.find('p' , class_='product-card__meta')
#                 liste.append(meta.get_text())
             word=meta.get_text().split()
             percent=word[2].replace("%" , " ")
             list_percent.append(percent)
             
                    

        
            
            
        return list_percent    
        
        
    def get_amount(self,products_content):
        self.products_content=products_content
        
        
        list_amount=[]
        
        for product in products_content:
             meta=product.find('p' , class_='product-card__meta')
#                 liste.append(meta.get_text())
             word=meta.get_text().split()
             amount=word[0].replace("cl" , " ")
             list_amount.append(amount)
             
                    

        
            
            
        return list_amount 
    
    
    def get_price(self,products_content):
        self.products_content=products_content
        
        
        list_prices=[]
        
        for product in products_content:
             meta=product.find('p' , class_='product-card__price')
#                 liste.append(meta.get_text())
             word=meta.get_text()
             price=word.replace("£" , " ")
             list_prices.append(price)
             
                    

        
            
            
        return list_prices

In [3]:
A=scrape()
sum_names=[]
sum_percents=[]
sum_amount=[]
sum_price=[]

for a in range(1,60):
    soup=A.scrape_html('https://www.thewhiskyexchange.com/c/40/single-malt-scotch-whisky', a)
    links=A.get_contents(soup)
    price_info=A.get_price_info(soup)
    names=A.get_names(links)
    percent=A.get_percent(links)
    amount=A.get_amount(links)
    price=A.get_price(price_info)
    sum_names+=names
    sum_percents+=percent
    sum_amount+=amount
    sum_price+=price
    
    
df = pd.DataFrame(list(zip(sum_names,sum_percents,sum_amount,sum_price)),
               columns =['Name', 'percent_alcohol','amount_by_cl','price_by_Pound'])

df

,Name,percent_alcohol,amount_by_cl,price_by_Pound
0,Deanston 18 Year Old,46.3,70,74.95
1,Lagavulin 12 Year OldSpecial Releases 2022,57.3,70,135
2,Laphroaig 10 Year OldCask Strength Batch 015,56.5,70,73.95
3,Lagavulin 16 Year Old,43,70,81.75
4,Balvenie 17 Year OldWeek of Peat,49.4,70,116
...,...,...,...,...
1411,Talisker Pure Malt Over 8 Year OldBot.1960s,45.7,75,"4,500"
1412,Clynelish 199326 Year Old Celebration of the ...,52.7,70,850
1413,Imperial 1990Celebration of the Cask,41.7,70,500
1414,Braes Of Glenlivet 197915 Year Old Sherry Cas...,59.2,75,900
1415,Ledaig 199722 Year Old Daily Dram,53.4,70,235

In [4]:
df.to_csv('C:\\Users\\aitma\\Desktop\\Data engineering project\\wisky.csv')